server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://47.98.183.4:3306/group1_gjj?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC

    username: group1
    password: 


    driver-class-name: com.mysql.cj.jdbc.Driver